[keyboard]
name = "rmk-sweep-ble"
product_name = "rmk-sweep-ble"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "nrf52840"

[layout]
rows = 4
cols = 10
layers = 3
keymap = [
  [
    [
      "Q",
      "W",
      "E",
      "R",
      "T",
      "Y",
      "U",
      "I",
      "O",
      "P",
    ],
    [
      "MT(A, LGui)",
      "MT(S, LAlt)",
      "MT(D, LCtrl)",
      "MT(F, LShift)",
      "G",
      "H",
      "MT(J, LShift)",
      "MT(K, LCtrl)",
      "MT(L, LAlt)",
      "MT(Semicolon, LGui)",
    ],
    [
      "Z",
      "X",
      "C",
      "V",
      "B",
      "N",
      "M",
      "Comma",
      "Dot",
      "Slash",
    ],
    [
      "_",
      "_",
      "_",
      "Enter",
      "LT(1, Escape)",
      "LT(2, Space)",
      "Backspace",
      "_",
      "_",
      "_",
    ],
  ],
  [
    [
      "Quote",
      "Minus",
      "Equal",
      "LeftBracket",
      "RightBracket",
      "Home",
      "PageDown",
      "PageUp",
      "End",
      "_",
    ],
    [
      "Kc0",
      "Kc1",
      "Kc2",
      "Kc3",
      "Kc4",
      "Left",
      "Down",
      "Up",
      "Right",
      "Backslash",
    ],
    [
      "Kc5",
      "Kc6",
      "Kc7",
      "Kc8",
      "Kc9",
      "_",
      "_",
      "_",
      "_",
      "Grave",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
  ],
  [
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "Home",
      "PageUp",
      "_",
      "_",
    ],
    [
      "Kc0",
      "Kc1",
      "Kc2",
      "Kc3",
      "Kc4",
      "Left",
      "Down",
      "Up",
      "Right",
      "_",
    ],
    [
      "Bootloader",
      "Kc6",
      "Kc7",
      "Kc8",
      "Kc9",
      "End",
      "PageDown",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
  ],
]

[behavior.combo]
timeout = "550ms"
combos = [
  { actions = [
    "A",
    "S",
  ], output = "Tab" },
  { actions = [
    "Z",
    "X",
  ], output = "Cut" },
  { actions = [
    "X",
    "C",
  ], output = "Copy" },
  { actions = [
    "C",
    "V",
  ], output = "Paste" },
  { actions = [
    "Q",
    "W",
  ], output = "Equal" },
]


# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation.
# Checkout doc here: https://rmk.rs/docs/user_guide/faq.html#my-matrix-is-row2col-the-matrix-doesn-t-work
# row2col = true

[ble]
enabled = true

[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "120ms", hold_timeout = "250ms", post_wait_time = "50ms" }

[split]
connection = "ble"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]

[split.central.matrix]
matrix_type = "direct_pin"
direct_pins = [
  [
    "P0_11",
    "P1_15",
    "P0_02",
    "P0_29",
    "P0_31",
  ],
  [
    "P1_13",
    "P1_11",
    "P0_10",
    "P0_09",
    "P0_06",
  ],
  [
    "P0_17",
    "P0_20",
    "P0_22",
    "P0_24",
    "P1_00",
  ],
  [
    "_",
    "_",
    "_",
    "P1_04",
    "P1_06",
  ],
]


[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]

[split.peripheral.matrix]
matrix_type = "direct_pin"
direct_pins = [
  [
    "P0_31",
    "P0_29",
    "P0_02",
    "P1_15",
    "P0_11",
  ],
  [
    "P0_06",
    "P0_09",
    "P0_10",
    "P1_11",
    "P1_13",
  ],
  [
    "P1_00",
    "P0_24",
    "P0_22",
    "P0_20",
    "P0_17",
  ],
  [
    "P1_06",
    "P1_04",
    "_",
    "_",
    "_",
  ],
]
